In [ ]:
!pip install numpy
!pip install matplotlib
!pip install scikit-learn
!pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 112.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 83.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 50.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 13.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 49.6 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitli

In [ ]:
import torch
lista = [[1,2,3],
         [4,5,6]]

tns = torch.tensor(lista)
print(tns.dtype)
print(tns)

ens = torch.FloatTensor(lista)
print(ens.dtype)
print(ens)

ens = torch.DoubleTensor(lista)
print(ens.dtype)
print(ens)

ens = torch.LongTensor(lista)
print(ens.dtype)
print(ens)

torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
import torch
import numpy as np

arr = np.random.rand(3,4)
arr = arr.astype(int)
print(arr)
print(arr.dtype)

print('')
tns = torch.from_numpy(arr)
print(tns)
print(tns.dtype)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
torch.int64


In [ ]:

tns1 = torch.ones(2, 3)
tns0 = torch.zeros(3, 5)
tnsr = torch.randn(3, 3)

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.0445, -0.2639,  0.0357],
        [ 0.3886,  1.1364, -0.3124],
        [-0.1518,  0.2721, -0.3923]])


In [ ]:
arr = tnsr.data.numpy()
print(arr)

[[ 0.04449905 -0.26393396  0.03573944]
 [ 0.38864145  1.1363633  -0.31235906]
 [-0.15176846  0.27208912 -0.3922973 ]]


In [ ]:
# tnsr[0,1]

print(tnsr[0:2, 2].data.numpy())
print(tnsr[0, 1].item())

[ 0.03573944 -0.31235906]
-0.2639339566230774


In [ ]:

tns1 = torch.randn(2,2,3)
tns2 = torch.ones(2,2,3)

print(tns1)
print(tns2)

print('')

print(tns1*tns2)

tensor([[[-0.6733, -1.2549, -1.4337],
         [ 0.2643, -0.1077, -1.1491]],

        [[ 0.3559, -2.2217, -0.8253],
         [-1.1373,  2.1916, -0.0481]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

tensor([[[-0.6733, -1.2549, -1.4337],
         [ 0.2643, -0.1077, -1.1491]],

        [[ 0.3559, -2.2217, -0.8253],
         [-1.1373,  2.1916, -0.0481]]])


In [ ]:

print(tns2.size())

print(tns2.view(tns2.size(0), -1))

torch.Size([2, 2, 3])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [ ]:

if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

print(device)
tns2 = tns2.to(device)
print(tns2)


cuda
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]], device='cuda:0')
